### ISSUE TITLE
Change Settings/About Page

### ISSUE THREAD

**Issue by polilluminato** [polilluminato/wassword-flutter#10]
Change the About Page to display more information like the [HabitKit App](https://www.habitkit.app/)

![Screenshot_2022-12-28-19-11-10-10_8573666834f651642185809836fc21a3](https://user-images.githubusercontent.com/202140/209855039-443c8f79-416a-4f3b-a598-84b68cfab6c8.jpg)

Create sections to organize information:
* General
* Developer
* Subscription

**Comment by polilluminato** [comment]
I created a moodboard on Behance to keep track of all inspirations [Wassword Settings Moodboard](https://www.behance.net/collection/200260853/Wassword-Settings)

**Comment by Dinokojt7** [comment]
Hi this about page is it on mobile or the website?

**Comment by polilluminato** [comment]
Hi @Dinokojt7 it's on the mobile version and also in the web version of the app, but it's only in the [develop](https://github.com/polilluminato/wassword-flutter/tree/develop) branch.
I'll plan to release to main in a couple of weeks

**Comment by Dinokojt7** [comment]
Alright cool, kindly assign to me
