### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [polilluminato/wassword-flutter#2]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by polilluminato** [comment]
Hi @Poussinou, I've already started the process to include Wassword in F-Droid, you can see the progress here: [com.albertobonacina.wassword](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9587)

**Comment by Poussinou** [comment]
It's currently live on F-Droid https://f-droid.org/packages/com.albertobonacina.wassword/

Maybe you can add a link in the readme to download it from there?

**Comment by polilluminato** [comment]
> It's currently live on F-Droid https://f-droid.org/packages/com.albertobonacina.wassword/
> 
> Maybe you can add a link in the readme to download it from there?

Yeah, I'll do it tomorrow 🤞🏼
