### ISSUE TITLE
Fdroid not supported anymore? 

### ISSUE THREAD

**Issue by lamyergeier** [polilluminato/wassword-flutter#23]
Could you please confirm if fdroid not support anymore?

**Comment by polilluminato** [comment]
@lamyergeier on F-Droid there is a old realease of Wassword. Next week I should have some time to update version 3.0 with some bug fixes and also release it on F-Droid.

**Comment by polilluminato** [comment]
Hi @lamyergeier. I've got some problems publishing on F-Droid but I create a release here on GitHub where you can download the apk and install it by yourself.

https://github.com/polilluminato/wassword-flutter/releases/tag/v27

If you are on a smartphone I think that the `app-arm64-v8a-release.apk` is the best for you. Thank you for your patience.

**Comment by lamyergeier** [comment]
Installed using obtainium. Thanks.
