### ISSUE TITLE
Missing Internet permission for About page

### ISSUE THREAD

**Issue by happy-turtle** [polilluminato/wassword-flutter#4]
The URLs in the about page lead to a net::ERR_CACHE_MISS because the main AndroidManifest is missing internet permissions. I think the exact same problem is described [here](https://stackoverflow.com/questions/60829199/flutter-webviews-gives-neterr-cache-miss-message)

Love the simplicity and style of your app by the way! 😊

**Comment by happy-turtle** [comment]
#5

**Comment by polilluminato** [comment]
Pull request merged on [88b9873](https://github.com/polilluminato/wassword-flutter/commit/88b98732bc6baf4766a9ab04f1ba24f2e9eb8270). Thanks @happy-turtle
